export const classOptions = [
    { value: 'Creche', label: 'Creche' },
    { value: 'Nursery 1', label: 'Nursery 1' },
    { value: 'Nursery 2', label: 'Nursery 2' },
    { value: 'KG 1', label: 'KG 1' },
    { value: 'KG 2', label: 'KG 2' },
    { value: 'Class 1', label: 'Class 1' },
    { value: 'Class 2', label: 'Class 2' },
    { value: 'Class 3', label: 'Class 3' },
    { value: 'Class 4', label: 'Class 4' },
    { value: 'Class 5', label: 'Class 5' },
    { value: 'Class 6', label: 'Class 6' },
    { value: 'JHS 1', label: 'JHS 1' },
    { value: 'JHS 2', label: 'JHS 2' },
    { value: 'JHS 3', label: 'JHS 3' },
];

export const feeTypeOptions = [
    { value: 'Tuition', label: 'Tuition' },
    { value: 'Books', label: 'Books' },
    { value: 'Uniform', label: 'Uniform' },
    { value: 'Transportation', label: 'Transportation' },
    { value: 'Feeding', label: 'Feeding' },
    { value: 'PTA', label: 'PTA'},
    { value: 'Sports', label: 'Sports' },
    { value: 'Dues', label: 'Dues' },
    { value: 'Examination', label: 'Examination' },
    { value: 'Extra_Classes', label: 'Extra Classes' },
    { value: 'Admission', label: 'Admission'},
];